ratemyrecipe/urls.py
from django.contrib import admin
from django.urls import path, include
from ratemyrecipeapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # If an empty string is entered after the server name, then the user is mapped to the index (home) page
    path('', views.index, name="index"),
    
    # This maps any URL beginning with 'ratemyrecipe/' to be handled by the ratemyrecipeapp urls
    path('ratemyrecipe/', include('ratemyrecipeapp.urls')),
    
    # This is the url mapping for the admin page
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratemyrecipeapp/urls.py
from django.urls import path
from ratemyrecipeapp import views

app_name = 'ratemyrecipeapp'

urlpatterns = [
        # If an empty string is provided as the url, this is mapped to the index page
        path('', views.index, name='index'),
        
        # URL for categories page
        path('categories/', views.categories, name="categories"),
        # URL for chosen_category page - is working fine
        path('categories/<slug:category_name_slug>/', views.chosen_category, name="chosen_category"),
        
        
        path('random_recipe/<slug:recipe_name_slug>/', views.random_recipe, name="random_recipe"),
        path('chosen_recipe/<slug:recipe_name_slug>/', views.chosen_recipe, name="chosen_recipe"),
        path('categories/<slug:category_name_slug>/<slug:recipe_name_slug>/', views.chosen_recipe, name="chosen_recipe"),
        
        
        path('trending/', views.trending, name="trending"),
        path('signUp/', views.sign_up, name="signUp"),
        path('login/', views.user_login, name="login"),
        path('logout/', views.user_logout, name='logout'),
        path('account/', views.my_account, name="account"),
        path('add_recipe/<slug:category_name_slug>/', views.add_recipe, name='add_recipe'),
        path('my_recipes/', views.my_recipes, name='my_recipes'),
        path('account/recipes_ive_rated/', views.recipes_ive_rated, name='recipes_ive_rated'),
        
        
        path('rate/', views.rate_recipe, name='rate-view'),
]

ratemyrecipeapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.validators import MaxValueValidator, MinValueValidator


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # I think we're not adding any other attributes like web or picture?

    def __str__(self):
        return self.user.username


class Category(models.Model):
    NAME_MAX_LENGTH = 30
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    slug = models.SlugField(unique=True)

    picture = models.ImageField(
        upload_to='category_images', blank=True, null=True
    )

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Recipe(models.Model):
    TITLE_MAX_LENGTH = 100
    TEXT_MAX_LENGTH = 1000
    TIME_NEEDED_MAX_LENGTH = len('HH:MM')

    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    picture = models.ImageField(
        upload_to='recipe_images'
    )

    ingredients = models.TextField(max_length=TEXT_MAX_LENGTH)
    directions = models.TextField(max_length=TEXT_MAX_LENGTH)
    is_vegan = models.BooleanField()
    is_vegetarian = models.BooleanField()
    cost = models.PositiveSmallIntegerField()
    time_needed = models.CharField(max_length=TIME_NEEDED_MAX_LENGTH)

    added_by = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if (self.cost < 0):
            self.cost = 0
        self.slug = slugify(self.title)
        super(Recipe, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'recipes'

    def __str__(self):
        return f'{self.title} by {self.added_by} in {self.category}'


class Rating(models.Model):
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    rated_by = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        # make sure that the rating is on the 1-5 range
        if self.rating < 1:
            self.rating = 1
        elif self.rating > 5:
            self.rating = 5

        super(Rating, self).save(*args, **kwargs)

    def __str__(self):
        return f'Rating for [{self.recipe}] by {self.rated_by}: {self.rating}'

ratemyrecipeapp/forms.py
from django import forms
from django.contrib.auth.models import User
from ratemyrecipeapp.models import Category, Recipe, Rating
from ratemyrecipeapp.models import UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=Category.NAME_MAX_LENGTH,
        help_text='Please enter the category name.'
    )
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    picture = forms.ImageField(
        help_text='Insert a category image here.'
    )

    class Meta:
        model = Category
        fields = ('name', 'picture', )


class RecipeForm(forms.ModelForm):
    error_message = 'Please enter the time in the format HH:MM. For example, 01:30 for an hour and a half.'

    title = forms.CharField(
        max_length=Recipe.TITLE_MAX_LENGTH,
        help_text='Recipe title'
    )
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    ingredients = forms.CharField(
        max_length=Recipe.TEXT_MAX_LENGTH,
        widget=forms.Textarea(attrs={'style': "width:100%;"}),
        help_text='What ingredients do you need?'
    )
    directions = forms.CharField(
        max_length=Recipe.TEXT_MAX_LENGTH,
        widget=forms.Textarea(attrs={'style': "width:100%;"}),
        help_text='How do you cook this amazing recipe?'
    )

    is_vegan = forms.BooleanField(required=False,
                                  help_text="Vegan Recipe")
    is_vegetarian = forms.BooleanField(required=False,
                                       help_text="Vegetarian Recipe")
    cost = forms.IntegerField(
        min_value=0,
        help_text='How much does this recipe cost?',
        error_messages={'invalid': 'Please enter a positive number.'},
    )
    time_needed = forms.CharField(
        max_length=Recipe.TIME_NEEDED_MAX_LENGTH,
        help_text='How long does it take to make this? (HH:MM)',
        # idk how to change this honestly
    )

    def clean_time_needed(self):
        time_needed = self.cleaned_data['time_needed']

        if len(time_needed) != Recipe.TIME_NEEDED_MAX_LENGTH:
            self.add_error(
                'time_needed',
                RecipeForm.error_message
            )

        return time_needed

    picture = forms.ImageField(
        help_text='Insert a photo of your recipe:'
    )

    class Meta:
        model = Recipe

        exclude = ('added_by', 'slug', 'category')


class RatingForm(forms.ModelForm):
    rating = forms.IntegerField(
        min_value=1, max_value=1,
        help_text='Rate this recipe!',
        # see other options in django-starfield
    )

    class Meta:
        model = Recipe
        exclude = ('recipe', 'rated_by', )


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', )


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ()

ratemyrecipeapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.db.models import Avg
from ratemyrecipeapp.models import Category, Recipe, Rating, UserProfile
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from ratemyrecipeapp.forms import RecipeForm, UserForm, UserProfileForm
from ratemyrecipe.settings import MEDIA_DIR
import os
from django.views.decorators.csrf import csrf_exempt
from django.template.defaulttags import register



def index(request):
    context_dict = {}
    
    # Picks a random recipe
    ran_recipe = Recipe.objects.order_by('?').first()
    # Gets all the ratings associated with that recipe
    ratings = Rating.objects.filter(recipe=ran_recipe)

    # Calculates the avergae rating and stores as a dictionary
    avg_rating_dict = ratings.aggregate(Avg('rating'))
    # Gets the value in the dict
    avg_rating = avg_rating_dict['rating__avg']
    
    if avg_rating is None:
        context_dict['rating'] = 1
    else:
        context_dict['rating'] = int(avg_rating)


    context_dict['Recipe'] = ran_recipe
    

    return render(request, 'ratemyrecipeapp/index.html', context=context_dict)


def categories(request):
    categories = list(Category.objects.all())
    
    files = os.listdir(os.path.join(MEDIA_DIR, "category_images/"))
    
    context_dict = {}
    context_dict['categories'] = categories
    context_dict['files'] = files

    return render(request, 'ratemyrecipeapp/categories.html', context=context_dict)


def chosen_category(request, category_name_slug):
    context_dict = {}

    # Tries to find category name slug with given name
    # If it can't, the get() method raises DoesNotExist exception
    # get() methods returns one model instance or raises exception
    category = Category.objects.get(slug=category_name_slug)

    # Retreives all associated recipes
    # filter() returns list of recipes objects or empty list
    recipes = Recipe.objects.filter(category=category)
        
    averages = []
    for recipe in recipes:
        ratings = Rating.objects.filter(recipe=recipe)
        avg_rating_dict = ratings.aggregate(Avg('rating'))
        avg_rating = avg_rating_dict['rating__avg']
        
        if avg_rating is None:
            averages.append(1)
        else:
            averages.append(int(avg_rating))
        
        
    context_dict['recipes'] = recipes
    context_dict['category'] = category
    context_dict['ratings'] = averages

    # renders and returns response to client
    return render(request, 'ratemyrecipeapp/chosen_category.html', context=context_dict)



def random_recipe(request, recipe_name_slug):
    context_dict = {}
    
    try:
        recipe = Recipe.objects.get(slug=recipe_name_slug)
        context_dict['recipe'] = recipe
        ratings = Rating.objects.filter(recipe=recipe)
        
        # Calculates the avergae rating and stores as a dictionary
        avg_rating_dict = ratings.aggregate(Avg('rating'))
        # Gets the value in the dict
        avg_rating = avg_rating_dict['rating__avg']
        
        
        if avg_rating is None:
            context_dict['rating'] = 1
        else:
            context_dict['rating'] = int(avg_rating)
        
    except:
        context_dict['recipe'] = None
    
    return render(request, 'ratemyrecipeapp/chosen_recipe.html', context=context_dict)


@csrf_exempt
def chosen_recipe(request, category_name_slug, recipe_name_slug):
    context_dict = {}
    
    try:
        recipe = Recipe.objects.get(slug=recipe_name_slug)
        context_dict['recipe'] = recipe
        ratings = Rating.objects.filter(recipe=recipe)
        
        # Calculates the average rating and stores as a dictionary
        avg_rating_dict = ratings.aggregate(Avg('rating'))
        # Gets the value in the dict
        avg_rating = avg_rating_dict['rating__avg']
        
        
        if avg_rating is None:
            context_dict['rating'] = 1
        else:
            context_dict['rating'] = int(avg_rating)
        
        
        
    except:
        context_dict['recipe'] = None
    
    return render(request, 'ratemyrecipeapp/chosen_recipe.html', context=context_dict)



def trending(request):
    context_dict = {}
    recipe_ratings={}

    
    for recipe in list(Recipe.objects.all()):
        rating_score=0
        no_rated=0
        for rating in list(Rating.objects.filter(recipe=recipe)):
            rating_score+=rating.rating
            no_rated+=1
        try:
            recipe_ratings[recipe]=(int(rating_score/no_rated))
        except:
            #recipe not added
            pass

    #amount of recipes to show
    amount=5
    sorted_values = sorted(recipe_ratings.values(), reverse=True)# Sort the values
    print(sorted_values)
    recipes = {}

    for i in range(amount):
        for k in recipe_ratings.keys():
            if recipe_ratings[k] == max(sorted_values):
                recipes[k] = recipe_ratings[k]
                del recipe_ratings[k]
                sorted_values.remove(max(sorted_values))
                break

    context_dict['recipes']=recipes
    context_dict['amount']=amount
   

    return render(request, 'ratemyrecipeapp/trending.html', context=context_dict)
    
    
def my_account(request):
    context_dict = {}
    
    return render(request, 'ratemyrecipeapp/my_account.html', context=context_dict)


@login_required
def add_recipe(request, category_name_slug):
    # Gets the recipe form from forms.py
    form = RecipeForm()

    if request.method == 'POST':
        form = RecipeForm(request.POST,request.FILES)
        u=request.user
        user=UserProfile.objects.get(user_id=u.id)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.added_by=user
            recipe.category = Category.objects.get(slug=category_name_slug)
            recipe.save()
            return redirect(reverse('ratemyrecipeapp:index'))

        else:
            print(form.errors)
    
    context_dict = {} 
    context_dict['form']=form
    context_dict['category']=Category.objects.get(slug=category_name_slug)

    return render(request, 'ratemyrecipeapp/add_recipe.html', context=context_dict)


def sign_up(request):
    # Is registration successful?
    registered = False

    if request.method == 'POST':
        # Attempt to grab info from raw form information
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save user's form data to database
            user = user_form.save()

            # Set then update password
            user.set_password(user.password)
            user.save()

            # Set commit=False to delay saving model
            # until ready to avoid integrity problems
            profile = profile_form.save(commit=False)
            profile.user = user

            # Saves UserProfile instance
            profile.save()

            # Update variable to indicate to template registration was successful
            registered = True
        else:
            # Invalid form(s)
            # Prints problems to terminal
            print(user_form.errors, profile_form.errors)
    else:
        # Not an HTTP POST so form rendered using two ModelForm instances
        # These forms will be blank, ready for user input
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render template depending on context
    return render(request,
                  'ratemyrecipeapp/sign_up.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):
    # If request is HTTP POST, try to pull relevant info
    if request.method == 'POST':
        # Get username and password from login form
        username = request.POST.get('username')
        password = request.POST.get('password')

        # If username/password combination valid, User object is returned
        user = authenticate(username=username, password=password)

        # If we have as User object, the details are correct
        # If None, no user with matching credential found
        if user:
            # Is account active?
            if user.is_active:
                # If account valid and active, log user in and send back to homepage
                login(request, user)
                return redirect(reverse('ratemyrecipeapp:index'))
            else:
                # An inactive account was used so doesn't log in
                return HttpResponse("Your RateMyRecipe account is disabled.")
        else:
            # Bad login details provided, so doesn't log in
            print("Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

    # The request is not HTTP POST, so display login form
    # This would be HTTP GET
    else:
        # No context variables to pass to template system so blank dict. object
        return render(request, 'ratemyrecipeapp/login.html')


@login_required
def user_logout(request):
    # Since we know user is logged in, we can just log them out
    logout(request)
    # Returns user to homepage
    return redirect(reverse('ratemyrecipeapp:index'))



@csrf_exempt
def rate_recipe(request):
    if request.method == 'GET':
        val = request.GET['val']
        u = request.user
        title = request.GET['title']
        
        # Gets the UserProfile associated with User
        user = UserProfile.objects.get(user=u)
        recipes = Recipe.objects.get(title=title)
            
        r = Rating.objects.create(
                rating=int(val),
                rated_by=user,

templates/ratemyrecipeapp/chosen_category.html
{% extends 'ratemyrecipeapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
{{ category.name}} - Rate My Recipe
{% endblock %}
{% block content %}
{% endblock %}

{% block nav %}

<li class="nav-item ">
    <a class="nav-link" href="{% url 'ratemyrecipeapp:index' %}">
        Home
    </a>

</li>
<li class="nav-item ">
    <a class="nav-link" href="{% url 'ratemyrecipeapp:categories' %}">
        Categories

    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'ratemyrecipeapp:trending' %}">Trending</a>
</li>
<li class="nav-item ">
    <a class="nav-link" href="{% url 'ratemyrecipeapp:account' %}">My Account</a>

</li>
{% endblock %}
{% block body_block %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">{{category.name}} Recipes</h1>
            <p>
                <a href="{% url 'ratemyrecipeapp:categories' %}" class="btn btn-primary my-2">Go back to Categories</a>
            </p>
            <p>
                {% if user.is_authenticated %}
                <a class="btn btn-primary my-2" href="{% url 'ratemyrecipeapp:add_recipe' category.slug %}">Add a recipe to {{ category.name }}</a>
                {% else %}
                <a href="{% url 'ratemyrecipeapp:login' %}" class="btn btn-primary my-2">Log in to add a recipe to {{ category.name }}</a>
                {% endif %}
            </p>
        </div>
    </div>
</section>

<div class="row row-cols-1 row-cols-sm-2 g-2">
    {% for r in recipes %}
    <div class="col">
        <div class="card shadow-sm">
            <a href="{% url 'ratemyrecipeapp:chosen_recipe' category.slug r.slug %}"><img src="/media/{{ r.picture }}" width="100%" height="350" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ r.name }}</text></img></a>
            <div class="card-body">
                <h4>{{ r.title }}</h4>
                <p id="avgrating">{{rating}}</p>

                <p class="card-text">{{ r.ingredients}}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'ratemyrecipeapp:chosen_recipe' category.slug r.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary">View Recipe</button></a>
                    </div>
                    <small class="text-muted">{{r.time_needed}}</small>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <h3> There are no recipes in this category yet.</h3>
    {% endfor %}

</div>
{% endblock %}

templates/ratemyrecipeapp/chosen_recipe.html
{% extends 'ratemyrecipeapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
{{recipe.title}} - Rate My Recipe
{% endblock %}
{% block content %}
{% endblock %}

{% block nav %}

<li class="nav-item">
    <a class="nav-link" href="{% url 'ratemyrecipeapp:index' %}">
        Home
    </a>

</li>
<li class="nav-item ">
    <a class="nav-link" href="{% url 'ratemyrecipeapp:categories' %}">
        Categories

    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'ratemyrecipeapp:trending' %}">Trending</a>
</li>
<li class="nav-item ">
    <a class="nav-link" href="{% url 'ratemyrecipeapp:account' %}">My Account</a>

</li>
{% endblock %}
{% block body_block %}

<div class="card text-white bg-secondary my-5 py-4 text-center">
    <div class="card-body">
        <h1 class="text-white m-0"><div id="title">{{ recipe.title }}</div></h1>
        

        <span id="hidden"><p id="avgrating">{{rating }}</p></span>

        <div class="stars">
            <span class="fa fa-star fa-3x checked"></span>
            <span class="fa fa-star fa-3x checked"></span>
            <span class="fa fa-star fa-3x checked"></span>
            <span class="fa fa-star fa-3x"></span>
            <span class="fa fa-star fa-3x"></span>
        </div>
        <p class="text-white m-0">Is vegan: {{ recipe.is_vegan }}</p>
        <p class="text-white m-0">Is vegetarian: {{ recipe.is_vegetarian }}</p>
        <a class="btn btn-primary" href="{% url 'ratemyrecipeapp:chosen_category' recipe.category.slug %}">Go back to category</a>
    </div>
</div>


<div class="row align-items-center my-5">
    
        <img class="img-fluid rounded mb-4 mb-lg-0" src="/media/{{ recipe.picture }}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">
        </text>
            <div class="col">
                <h3>Ingredients:</h3>
                <p class="text-black m-0">{{ recipe.ingredients }}</p>
                <p class="text-black m-0">Cost: £{{ recipe.cost }}</p>

            </div>

            <div class="col">
                <h3>Method:</h3>

                <p class="text-black m-0">{{ recipe.directions }}</p>
                <p class="text-black m-0">Time: {{ recipe.time_needed }}</p>

            </div>

    {% if user.is_authenticated %}
    <div class="col">
        <h3>How would you rate this recipe?</h3>
        <form class="rate-form" method="POST" action="{%url 'ratemyrecipeapp:chosen_recipe' recipe.slug %}" id="{{object.id}}">
            {% csrf_token %}
            <button type="submit" class="fa fa-star fa-3x my-btn" id="first"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="second"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="third"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="fourth"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="fifth"></button>
        </form>
        <br>
        <div id="confirm-box"></div>
    </div>
    </div>


    {% endif %}
    {% endblock %}

templates/ratemyrecipeapp/index.html
{% extends 'ratemyrecipeapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
Home - Rate My Recipe
{% endblock %}
{% block content %}
{% endblock %}

{% block nav %}

<li class="nav-item active">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:index' %}">Home
                        <span class="sr-only">(current)</span>
                        </a>
                           
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:categories' %}">
                        Categories
                        
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:trending' %}">Trending</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:account' %}">My Account</a>
                        
                    </li>
{% endblock %}
{% block body_block %}
<div class="card text-white bg-secondary my-5 py-4 text-center">
            <div class="card-body">
{% if user.is_authenticated %}
                <!--Relies on user model-->
                <p class="text-white m-0">Welcome back to Rate My Recipe, {{ user.username }}!</p>
                <a class="btn btn-primary" href="{% url 'ratemyrecipeapp:account' %}">Go to my account</a>
                {% else %}
                <p class="text-white m-0">Welcome to Rate My Recipe!</p>
                {% endif %}
            </div>
        </div>
        <div class="row align-items-center my-5">
            <div class="col-lg-7">
                <h1 class="font-weight-light">Why not try...</h1>
                <img class="img-fluid rounded mb-4 mb-lg-0" src="/media/{{Recipe.picture}}"" width="900" height="400" alt="">


            </div>


            <!-- /.col-lg-8 -->
        {% if Recipe %}
            <div class="col-lg-5">
                <h1 class="font-weight-light">{{ Recipe.title }}</h1>
				
				<span id="hidden"><p id="avgrating">{{rating }}</p></span>
				<div class="stars">
					<span class="fa fa-star fa-3x"></span>
					<span class="fa fa-star fa-3x"></span>
					<span class="fa fa-star fa-3x"></span>
					<span class="fa fa-star fa-3x"></span>
					<span class="fa fa-star fa-3x"></span>
				</div>
				<br>
				
                <a class="btn btn-primary" href="{% url 'ratemyrecipeapp:random_recipe' Recipe.slug %}">Go to Recipe</a>
            </div>
        </div>
        {% else %}
            <p> Sorry, there are no recipes available now.</p>
        {% endif %}
        <div class="col-md-4 mb-5">
			{% if user.is_authenticated %}
				<a class="btn btn-primary" href="{% url 'ratemyrecipeapp:logout' %}">Logout</a>
			{% else %}
				<a class="btn btn-primary" href="{% url 'ratemyrecipeapp:login' %}">Login</a>
                <a class="btn btn-primary" href="{% url 'ratemyrecipeapp:signUp' %}">Sign Up</a>
			{% endif %}
</div>
</div>
{% endblock %}

templates/ratemyrecipeapp/my_account.html
{% extends 'ratemyrecipeapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
My Account - Rate My Recipe
{% endblock %}

{% block content %}
{% endblock %}

{% block nav %}
<li class="nav-item ">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:index' %}">Home</a>
                            
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:categories' %}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:trending' %}">Trending</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:account' %}">My Account</a>
                        <span class="sr-only">(current)</span>
                    </li>
{% endblock %}

{% block body_block %}
<div class="card text-white bg-secondary my-5 py-4 text-center">
			<div class="card-body">

{% if user.is_authenticated %}
			<p>
				<br class="text-white m-0">Welcome to Rate My Recipe, {{ user.username }}!</br>
				</p>
				<div ><p>
	<a class="btn btn-primary" href="{% url 'ratemyrecipeapp:my_recipes' %}">My Recipes</a>
</p>
				</div>

				<div>
					<p>
						<a class="btn btn-primary" href="{% url 'ratemyrecipeapp:recipes_ive_rated' %}">My Ratings</a>
					</p>
				</div>
				<div>
					<p>
					<a class="btn btn-primary" href="{% url 'ratemyrecipeapp:logout' %}">Logout</a>
					</p>
				</div>
				
			{% else %}
				
				<p class="text-white m-0">Welcome to Rate My Recipe!</p>
				<p class="text-white m-0">Log In or Sign up here!</p>
				<a class="btn btn-primary" href="{% url 'ratemyrecipeapp:login' %}">Login</a>
				<a class="btn btn-primary" href="{% url 'ratemyrecipeapp:signUp' %}">Sign Up</a>
				
			{% endif %}
</div>
</div>
		
{% endblock %}