ratemyrecipe/urls.py
from django.contrib import admin
from django.urls import path, include
from ratemyrecipeapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # If an empty string is entered after the server name, then the user is mapped to the index (home) page
    path('', views.index, name="index"),
    
    # This maps any URL beginning with 'ratemyrecipe/' to be handled by the ratemyrecipeapp urls
    path('ratemyrecipe/', include('ratemyrecipeapp.urls')),
    
    # This is the url mapping for the admin page
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratemyrecipeapp/urls.py
from django.urls import path
from ratemyrecipeapp import views

app_name = 'ratemyrecipeapp'

urlpatterns = [
        # If an empty string is provided as the url, this is mapped to the index page
        path('', views.index, name='index'),
        
        # URL for categories page
        path('categories/', views.categories, name="categories"),
        # URL for chosen_category page - is working fine
        path('categories/<slug:category_name_slug>/', views.chosen_category, name="chosen_category"),
        
        
        path('random_recipe/<slug:recipe_name_slug>/', views.random_recipe, name="random_recipe"),
        path('chosen_recipe/<slug:recipe_name_slug>/', views.chosen_recipe, name="chosen_recipe"),
        path('categories/<slug:category_name_slug>/<slug:recipe_name_slug>/', views.chosen_recipe, name="chosen_recipe"),
        
        
        path('trending/', views.trending, name="trending"),
        path('signUp/', views.sign_up, name="signUp"),
        path('login/', views.user_login, name="login"),
        path('logout/', views.user_logout, name='logout'),
        path('account/', views.my_account, name="account"),
        path('add_recipe/<slug:category_name_slug>/', views.add_recipe, name='add_recipe'),
        path('my_recipes/', views.my_recipes, name='my_recipes'),
        path('account/recipes_ive_rated/', views.recipes_ive_rated, name='recipes_ive_rated'),
        
        
        path('rate/', views.rate_recipe, name='rate-view'),
]

templates/categories.html
<!doctype html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>Rate My Recipe - Categories</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">



    <!-- Bootstrap core CSS -->
    <link href="{% static '/assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap/css/small-business.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'ratemyrecipeapp:index' %}">Rate My Recipe</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:index' %}">
                            Home
                        </a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:categories' %}">Categories<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:trending' %}">Trending</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:account' %}">My Account</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>


        <div class="album py-5 bg-light">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 g-2">
                    {% for c in categories %}

                        <div class="col">
                            <div class="card shadow-sm">
                                <a href="{% url 'ratemyrecipeapp:chosen_category' {{ c.slug }}  %}"><img src="{% static 'images/Categories/{{ urls.c }}' %}" width="100%" height="350" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ c.name }}</text></img></a>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
                </div>

    </main>



    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy;Website 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>

templates/chosen_category.html
<!doctype html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>Rate My Recipe - Categories</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">



    <!-- Bootstrap core CSS -->
    <link href="{% static '/assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap/css/small-business.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


</head>
<body>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{c.name}}</h1>
                <p>
                    <a href="{% url 'ratemyrecipeapp:categories' %}" class="btn btn-primary my-2">Go back to Categories</a>
                </p>
            </div>
        </div>
    </section>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'ratemyrecipeapp:index' %}">Rate My Recipe</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:index' %}">
                            Home
                        </a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:categories' %}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:trending' %}">Trending</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:account' %}">My Account</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>



        <div class="album py-5 bg-light">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 g-2">
                    {% for r in recipes %}

                    <div class="col">
                        <div class="card shadow-sm">
                            <a href="{% url 'ratemyrecipeapp:chosen_recipe' r.slug  %}"><img src="{% static 'images/Categories/{{ urls.r }}' %}" width="100%" height="350" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ r.name }}</text></img></a>
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'ratemyrecipeapp:chosen_recipe' r.slug  %}">View</button>
                                    </div>
                                    <small class="text-muted">9 mins</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>


    </main>



    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>

templates/home.html
{% extends 'rate_my_recipe/base.html' %}
{% block title_block %}
Home
{% endblock %}
{% block body_block%}
<h1>Rango says...</h1>
<div>
    {% if user.is_authenticated %}
    <!--Relies on user model-->
    Welcome back to Rate My Recipe, {{ user.first_name }}!
    <a href="{% url 'rate_my_recipe:account' %}">Go to my account</a>
    {% else %}
    Welcome to Rate My Recipe
    {% endif %}
    </br>
    <strong>Why not try...</strong>
</div>
<div>
    <!--Need to add implementation for random recipes-->
    <img src="{% static 'images/{{recipes}}.jpg' %}"
         alt="Recipe" />
</div>
<div>
    <ul>
        {% if user.is_authenticated %}
        <!-- Show these links when the user is logged in -->
        <li><a href="{% url 'rango:logout' %}">Log out</a></li>
        {% else %}
        <!-- Show these links when the user is NOT logged in -->
        <li><a href="{% url 'rango:login' %}">Login</a></li>
        <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
        {% endif %}
    </ul>
</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Home - Rate My Recipe</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap/css/small-business.css' %}" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Rate My Recipe</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:categories' %}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:trending' %}">Trending</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ratemyrecipeapp:account' %}">My Account</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <!-- Page Content -->
    <div class="container">

        <!-- Heading Row -->
        <!-- Call to Action Well -->
        <div class="card text-white bg-secondary my-5 py-4 text-center">
            <div class="card-body">
                {% if user.is_authenticated %}
                <!--Relies on user model-->
                <p class="text-white m-0">Welcome back to Rate My Recipe, {{ user.username }}!</p>
                <a class="btn btn-primary" href="{% url 'ratemyrecipeapp:account' %}">Go to my account</a>
                {% else %}
                <p class="text-white m-0">Welcome to Rate My Recipe!</p>
                {% endif %}
            </div>
        </div>
        <div class="row align-items-center my-5">
            <div class="col-lg-7">
                <h1 class="font-weight-light">Why not try...</h1>
                <img class="img-fluid rounded mb-4 mb-lg-0" src="http://placehold.it/900x400" alt="">
            </div>


            <!-- /.col-lg-8 -->
            <div class="col-lg-5">
                <h1 class="font-weight-light">{{Recipe.title}}</h1>
				<h3>{{rating}}</h3>
                <!--recipe details would be here-->
                <a class="btn btn-primary" href="{% url 'ratemyrecipeapp:categories' %}">Go to Recipe</a>
            </div>
        </div>
        <div class="col-md-4 mb-5">
			{% if not user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'ratemyrecipeapp:login' %}">Login</a>
                <a class="btn btn-primary" href="{% url 'ratemyrecipeapp:signUp' %}">Sign Up</a>
			{% endif %}
        </div>

        </div>

        <!-- /.container -->
        <!-- Footer -->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
            </div>
            <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>